### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by winlex** [winlex/System-of-linear-equations#1]
### Сделать проверку на ввод
- [ ] Разрешить клавиши: enter, backspace и space;
- [ ] Разрешить ввод только английских букв;
- [ ] Разрешить клавиши: минус, плюс, равно, точка(плавающая запятая), умножить и точку с запятой;
- [ ] Сделать проверку на повторяющиеся символы: минуса, плюса, умножить, равно и точки с запятой;
